<form method="post" enctype="multipart/form-data"action="submitAddProduct">
    
        <button type="reset" value="reset">Annuler les modifications</button>
        <button type="submit"value="submitAddProduct" >Valider et enregister la fiche</button>
   
    <fieldset>
        <legend>Gestion</legend>
        <p>
            <label>Statut</label>
            <!-- récupérer les statuts -->
        </p>
        <p>
            <input type="radio" class="grey" checked name="statut" value="En attente" id="radio1"/><label for="radio1">En attente de mise en ligne</label>
        </p>
        <p>
            <input type="radio"class="green" name="statut" value="En boutique" id="radio2"/><label for="radio2">En boutique</label>
        </p>
        <p>
           <input type="radio" class="red" name="statut" value="Retiré" id="radio3"/><label for="radio3">Retiré</label>
        </p>
        
        <p> 
            <label>Boutique</label>
            <select name='boutique'>
                <option>Choisir une boutique ...</option>
                <?php foreach($boutiques as $boutique): ?>
                    <option value="<?= htmlspecialchars($boutique['id_boutique']) ?>"><?= htmlspecialchars($boutique['nom']) ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        
        <p>
             <label>Rayon</label>
             <select name='rayon'>
                 <option>Choisir un rayon...</option>
                <?php foreach($rayons as $rayon): ?>
                    <option value="<?= htmlspecialchars($rayon['id_rayon']) ?>"><?= htmlspecialchars($rayon['nom']) ?></option>
                <?php endforeach; ?>
            </select>
        </p>
        </fieldset>
        
        <fieldset>
            <legend>Présentation</legend>
            <p>
                <label for="nom">Nom du produit</label><input type="text" name="nom" id="nom"/>
            </p>
            <p>
                <label for="marque">Marque</label><input type="text" name="marque" id="marque"/>
            </p>
            <p>
                <label for="refproduit">Référence du produit</label><input type="text" name="refproduit" id="refproduit"/>
            </p>
            <p>
                <label for="etiquette">Etiquettes</label><input type="text" name="etiquette" id="etiquette"/>
            </p>
    
      <p>
         <label for="Prix">Prix
         <label for="prix">Prix<input type="number" step="0.01" name="prix" id="prix"/> €  </label>
         <label for="ecopart">éco-participation <input type="number" step="0.01" name="ecopart" id="ecopart"/> €  </label>
            </label>
            <p>
                 <label for="description">Description principale (MarkDown)</label>
            </p> 
                
            <p>
                 <textarea name="description" id="description" rows="5" cols="33"> </textarea>
            </p>
        
          </p>
        </fieldset>
        
        <fieldset>
            <legend>Photos</legend>
            <p>
                
            
             <label for="image1">Photo 1</label><input type="file" name="image1" id="image1" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
             </p>
             <p>
             <label for="file">Photo 2</label><input type="file" name="image2" id="image2" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
             </p>
             <p>
             <label for="file">Photo 3</label><input type="file" name="image3" id="image3" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
             </p>
             <p>
             <label for="file">Photo 4</label><input type="file" name="image4" id="image4" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
             </p>
             <p>
             <label for="file">Photo 5</label><input type="file" name="image5" id="image5" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
             </p>
        </fieldset>
            
    <fieldset>
        <legend>Descriptif 1</legend>
        <p>
        <label for="titre1">Titre</label><input type="text" name="titre1"/>
        </p>
        <p>
        <label for="file">Image</label><input type="file" name="imaged1" id="imaged1" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
        </p>
        <p>
        <label for="texte1">Texte</label>
        </p>
        <p>
        <textarea name="texte1" id="texte1" rows="5" cols="33"> </textarea>
        </p>
    </fieldset>
    
    <fieldset>
        <legend>Descriptif 2</legend>
        <p>
            <label for="titre2">Titre</label><input type="text" name="titre2"/>
        </p>
        <p>
            <label for="file">Image</label><input type="file" name="imaged2" id="imaged2" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
        </p>
        <p>
            <label for="texte2">Texte</label>
        </p>
        <p>
            <textarea name="texte2" id="texte2" rows="5" cols="33"> </textarea>
        
            
        </p>
    </fieldset>
    
     <fieldset>
        <legend>Descriptif 3</legend>
        <p>
            <label for="titre3">Titre</label><input type="text" name="titre3"/>
        </p>
        <p>
            <label for="file">Image</label><input type="file" name="imaged3" id="imaged3" placeholder="Choisir un fichier" accept="image/png, image/jpeg">
        </p>
         <p>
            <label for="texte3">Texte</label>
         </p>
         <p>
             <textarea name="texte3" id="texte3" rows="5" cols="33"> </textarea>
        </p>
    </fieldset>
    
    
  
    
</form>