<div class="container">
    <!-- attention voir si on doit deplacer container -->
    <div class="product">
        <h1 class="prodname">
           <?= $displayed['marque'] ?> <?= $displayed['nom'] ?>
        </h1>
        <div class="menuprod">
            <ul>
                <li><a href="#presentation">Présentation</a></li>
                <li><a href="#descript">Descriptif</a></li>
                <li><a href="#specs">Caractériques techniques</a></li>
            </ul>
        </div>

        <section id="presentation" class="present">
            <h2>Presentation</h2>
            <div class="tags">
                <span class="tag"><?= $displayed['reference'] ?> </span>
                <span class="tag">7 ms</span>
                <span class="tag">Format large 16/9<sup>e</sup></span>
                <span class="tag">HDMI</span>
                <span class="tag">VGA</span>
                <span class="tag">Noir</span>
            </div>
        </section>
                <div class="brand"><?= $displayed['marque'] ?></div>


        <section class="show">
            <!-- [ viewer photos ] [ bloc "pricebox" + bloc "arguments" ]--->
            
           <div id="viewer" class="slideshow">
               <!--<div id='bigImage'></div>
               
               <div>Images non contractuelles</div>
               
               <div id='smallImages' class='smallI'></div>
              <?php //foreach($photos as $photo): ?>
             <img class="photos" src="<?php //$photo['src'] ?>" data-id="<?php//$photo['id_photo']?>" alt="<?php//$photo['alt']?>">
               <?php //endforeach; ?>
               </div>-->
               
            </div> <!-- End [ viewer ] -->
        
            
              <!-- [bloc "pricebox""]--->
               <div class="pricebox"><span class="price"><?= $displayed['prix'] ?></span>
                    <div class="shopbtn">
                        <button class="addToCart" name="addToCart" >Ajouter au panier</button>
                        <button class="addToWish" name="addToWish" >Ajouter à ma liste d'envies</button>
                    </div>

                    <div class="waranty">Garantie 2 ans vendeur</div>
                    <div class="arguments"><?=$displayed['description_principale']?></div> <!--end argts  -->
                </div>  <!--end pricebox -->


        </section>
        <!--end prodbox  -->
        <section id="descript" class="present">
            <h2>Descriptif </h2>
            <div>
                <h3>
                    <?=$displayed['titre_1']?>
                </h3>
                <img src="<?=$displayed['image_1']?>" alt="taille de l'écran" class="main-right">
                <!-- image_1 -->
                <p>
                    <?=$displayed['description_1']?>
                </p>

                <!--<div class="clear"></div>-->
            </div>
            <div>
                <h2>
                    <?=$displayed['titre_2']?>
                </h2>
                <img src="<?=$displayed['image_2']?>" alt="zoom écran" class="main-left">
                <p>
                    <?=$displayed['description_2']?>
                </p>
            </div>
            <!--<div class="clear"></div>-->
            <div>
                <h2>
                    <?=$displayed['titre_3']?>
                </h2>
                <img src="<?=$displayed['image_3']?>" alt="écran" class="main-right">
                <p>
                    <?=$displayed['description_3']?>
                </p>
        </section>


        <!-- Caractèristiques technique-->
        <section id="specs" class="present">
          <h2 class="specs"></h2>
          <div class="tab">
        <div>
            <h3>Affichage</h3>
            <table>
                <tr>
                    <td>Taille de l'écran</td>
                    <td> 23.8 pouces</td>
                </tr>
                <tr>
                    <td>Format de l'écran</td>
                    <td> 16/9</td>
                </tr>
                <tr>
                    <td>Type de Dall</td>
                    <td> Dalle IPS</td>
                </tr>
                <tr>
                    <td>Technologie LCD</td>
                    <td> IPS</td>
                </tr>
                <tr>
                    <td>Résolution Max</td>
                    <td> 1920 x 1080 pixels</td>
                </tr>
                <tr>
                    <td>Dot Pitch</td>
                    <td> 0.2745 mm</td>
                </tr>
                <tr>
                    <td>Luminosité</td>
                    <td> 250 cd/m²</td>
                </tr>
                <tr>
                    <td>Contraste</td>
                    <td> 20000000 /1</td>
                </tr>
                <tr>
                    <td>Temps de réponse</td>
                    <td> 7 ms</td>
                </tr>
                <tr>
                    <td>Angle de vision (horizontal)</td>
                    <td> 178 Degré(s)</td>
                </tr>
                <tr>
                    <td>Angle de vision (vertical)</td>
                    <td> 178 Degré(s)</td>
                </tr>
                <tr>
                    <td>Dalle mate/antireflets</td>
                    <td> Oui</td>
                </tr>
                <tr>
                    <td>NVIDIA G-SYNC</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Adaptive-Sync</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>AMD FreeSync</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Flicker-Free</td>
                    <td> Oui</td>
                </tr>
                <tr>
                    <td>Anti-lumière bleue</td>
                    <td> Oui</td>
                </tr>
            </table>
        </div>
        <div>
            <h3>Ecran</h3>
            <table>
                <tr>
                    <td>Type d'écran</td>
                    <td> LED</td>
                </tr>
                <tr>
                    <td>Ecran large</td>
                    <td> Oui</td>
                </tr>
                <tr>
                    <td>Ecran incurvé</td>
                    <td>Non</td>
                </tr>
                <tr>
                    <td>Borderless</td>
                    <td> Oui</td>
                </tr>
                <tr>
                    <td>Compatible 3D</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Ecran tactile</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Fréquence verticale mini</td>
                    <td> 60 Hz</td>
                </tr>
                <tr>
                    <td>Type d'activités</td>
                    <td> Bureautique</td>

                </tr>
            </table>
        </div>
        <div>
            <h3>Ergonomie</h3>
            <table>
                <tr>
                    <td>Pivot</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Pied réglable en hauteur</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Pied amovible</td>
                    <td> Oui</td>
                </tr>
                <tr>
                    <td>Fixation VESA</td>
                    <td> N/A</td>
                </tr>
                <tr>
                    <td>Angle inclinaison vers l'arrière (haut)</td>
                    <td> 21.5 Degré(s)</td>
                </tr>
                <tr>
                    <td>Angle inclinaison vers l'avant (bas)</td>
                    <td> 3.5 Deg</td>
                </tr>
                <tr>

                </tr>
            </table>
        </div>
        <div>
            <h3>Connectique</h3>
            <table>
                <tr>
                    <td>Entrées vidéo</td>
                    <td> 1 X HDMI Femelle, 1 X VGA (D-sub 15 Femelle)</td>
                </tr>
                <tr>
                    <td>Entrée audio</td>
                    <td>Aucun(e)</td>
                </tr>
                <tr>
                    <td>Sorties audio</td>
                    <td> 1 X Line OUT (Jack 3.5mm Femelle)</td>
                </tr>
            </table>
        </div>
        <div>
            <h3>Multimedia</h3>
            <table>
                <tr>
                    <td>H.P. Intégrés</td>
                    <td> Non</td>
                </tr>
                <tr>
                    <td>Webcam</td>
                    <td>Non</td>
                </tr>
                <tr>
                    <td>Tuner TV</td>
                    <td>Non</td>
                </tr>
                <tr>
                </tr>
            </table>
        </div>
        <div>
            <h3>caractéristiques physiques</h3>
            <table>
                <tr>
                    <td>Couleur</td>
                    <td> Noir</td>
                </tr>
                <tr>
                    <td>Largeur</td>
                    <td> 540.1 mm</td>
                </tr>
                <tr>
                    <td>Hauteur</td>
                    <td> 417.4 mm</td>
                </tr>
                <tr>
                    <td>Profondeur</td>
                    <td> 186.8 mm</td>
                </tr>
                <tr>
                    <td>Poids</td>
                    <td> 2.48 kg</td>
                </tr>
                <tr>
                    <td>Pack multi-écrans</td>
                    <td> Non</td>
                </tr>
            </table>
        </div>
        <div>
            <h3>Alimentation</h3>
            <table>
                <tr>
                    <td>Consommation</td>
                    <td> 25 W</td>
                </tr>
                <tr>
                    <td>Consommation en veille</td>
                    <td> 0.5 W</td>
                </tr>
                <tr>
                    <td>Alimentation interne</td>
                    <td> Non</td>
                </tr>
            </table>
        </div>
    </div>

</section>


        </div>
    </div>