      <div class="product">
        <h1 class="prodname"> <!--<?=// {$produits[$marque]} ?><?=// {$produits[$nom]}  ?>--> (AOC 24B1XHS)</h1>
        <div class="menuprod">
          <ul>
            <li><a href="#presentation">Présentation</a></li>
            <li><a href="#descript">Descriptif</a></li>
            <li><a href="#specs">Caractériques techniques</a></li>
          </ul>
        </div>
        <section id="presentation" class="present">
          <h2>Presentation</h2>
          <div class="tags"> <span class="tag">1920 x 1080px</span> <span class="tag">7 ms</span> <span class="tag">Format large 16/9<sup>e</sup></span> <span class="tag">HDMI</span> <span class="tag">VGA</span> <span class="tag">Noir</span>
          </div>
		 </section>
		 <section class="prodbox"> <!-- [ viewer photos ] [ bloc "pricebox" + bloc "arguments" ]--->
		   <div id="viewer"><!-- [viewer photos] [bloc "pricebox" + bloc "arguments"]--->
              <div id="slider1" style="max-width:768px;  max-height:768px; margin: 0 auto;">
            
              </div>
          </div><!-- End slide [ viewer ] -->
          <!-- [bloc "pricebox""]--->
		  <div class="pricebox"><!-- <?= //$prix ?> -->
              <div id="shopbtn">
                  <button class="btn-info btn-block addToCart" name="addToCart" value="Ajouter au panier"></button>
                  <button class="addToWish" name="addToWish" value="Ajouter à ma liste d'envies"></button>
			  </div>
              <div class="waranty">Garantie 2 ans vendeur</div>
          </div> <!--end pricebox -->
		  <div class="arguments"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, rem, quibusdam. Numquam et, veritatis aliquam minus dolores quas, deserunt. Quidem tenetur eum debitis officia nulla ex vel veniam suscipit ea.
            <ul>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
            </ul>
          </div> <!--end argts  --> 
        </section><!--end prodbox  -->
		<section id="desriptif" class="present">
          <h2>Description </h2>
          <div>
            <h3> Un moniteur Full HD performant et tout en finesse </h3>
            <img src="images/product-1/screen.png" alt="taille de l'écran" class="main-right"><!-- image_1 -->
			  <p><!-- description_1 --></p>
            <p> Issu de la série B1, le moniteur AOC 24B1XHS dispose de tous les atouts indispensables pour offrir une expérience utilisateur agréable. Son écran Full HD de 23.8" s'accompagne d'une dalle IPS ainsi que d'un temps de réponse de 7 ms
              pour une image toujours performante. Aussi, le 24B1XHS séduit par son profil plat et son design sans contour qui favorise le plaisir visuel et l'immersion. Ce moniteur WLED trouvera facilement une place de choix sur votre bureau
              pour toutes vos utilisations quotidiennes. </p>
            <!--<div class="clear"></div>-->
          </div>
          <div>
            <h2>Appréciez le design sans contour </h2>
            <img src="img/product-1/desc-1.jpg" alt="zoom écran" class="main-left">
            <p>En plus du look moderne et attrayant qu'il procure, le design sans contour permet des configurations à plusieurs écrans sans interruption. Votre curseur, vos fenêtres ne sont plus perdus dans les abysses sombres des contours lorsque
              plusieurs écrans sont placés les uns à côté des autres. </p>
            <p> Le profil plat de ce moniteur AOC offre de nombreux avantages. Très élégant sous tous les angles, il devient un choix idéal dans les espaces publics. Sa finesse et sa conception moderne lui permettent d'occuper moins de place sur le bureau. </p>
          </div>
          <!--<div class="clear"></div>-->
          <div>
            <h2>Tout le confort nécessaire</h2>
            <img src="img/product-1/desc-2.jpg" alt="écran" class="main-right">
            <p> Agréable visuellement et intuitif, ce moniteur dispose également d'une dalle IPS. Cette dernière reproduit des couleurs éclatantes et offre de très larges angles de vue. De cette façon, les images gardent toujours un excellent aspect et une parfaite précision,
              quel que soit l'angle auquel vous regardez l'écran. </p>
            <p> Vous voulez utiliser votre écran même dans un environnement très lumineux, à côté d'une fenêtre au soleil par exemple ? La haute luminosité de 250 cd/m² garantit une bonne visibilité, même en conditions difficiles. </p>
          </div>
        </section>
      </div>
      <!-- END PRODUCT -->  
      </div><!-- end product -->       <div class="product">
        <h1 class="prodname"> <!--<?=// {$produits[$marque]} ?><?=// {$produits[$nom]}  ?>--> (AOC 24B1XHS)</h1>
        <div class="menuprod">
          <ul>
            <li><a href="#presentation">Présentation</a></li>
            <li><a href="#descript">Descriptif</a></li>
            <li><a href="#specs">Caractériques techniques</a></li>
          </ul>
        </div>
        <section id="presentation" class="present">
          <h2>Presentation</h2>
          <div class="tags"> <span class="tag">1920 x 1080px</span> <span class="tag">7 ms</span> <span class="tag">Format large 16/9<sup>e</sup></span> <span class="tag">HDMI</span> <span class="tag">VGA</span> <span class="tag">Noir</span>
          </div>
		 </section>
		 <section class="prodbox"> <!-- [ viewer photos ] [ bloc "pricebox" + bloc "arguments" ]--->
		   <div id="viewer"><!-- [viewer photos] [bloc "pricebox" + bloc "arguments"]--->
              <div id="slider1" style="max-width:768px;  max-height:768px; margin: 0 auto;">
            
              </div>
          </div><!-- End slide [ viewer ] -->
          <!-- [bloc "pricebox""]--->
		  <div class="pricebox"><!-- <?= //$prix ?> -->
              <div id="shopbtn">
                  <button class="btn-info btn-block addToCart" name="addToCart" value="Ajouter au panier"></button>
                  <button class="addToWish" name="addToWish" value="Ajouter à ma liste d'envies"></button>
			  </div>
              <div class="waranty">Garantie 2 ans vendeur</div>
          </div> <!--end pricebox -->
		  <div class="arguments"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, rem, quibusdam. Numquam et, veritatis aliquam minus dolores quas, deserunt. Quidem tenetur eum debitis officia nulla ex vel veniam suscipit ea.
            <ul>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
              <li></li>
            </ul>
          </div> <!--end argts  --> 
        </section><!--end prodbox  -->
		<section id="desriptif" class="present">
          <h2>Description </h2>
          <div>
            <h3> Un moniteur Full HD performant et tout en finesse </h3>
            <img src="images/product-1/screen.png" alt="taille de l'écran" class="main-right"><!-- image_1 -->
			  <p><!-- description_1 --></p>
            <p> Issu de la série B1, le moniteur AOC 24B1XHS dispose de tous les atouts indispensables pour offrir une expérience utilisateur agréable. Son écran Full HD de 23.8" s'accompagne d'une dalle IPS ainsi que d'un temps de réponse de 7 ms
              pour une image toujours performante. Aussi, le 24B1XHS séduit par son profil plat et son design sans contour qui favorise le plaisir visuel et l'immersion. Ce moniteur WLED trouvera facilement une place de choix sur votre bureau
              pour toutes vos utilisations quotidiennes. </p>
            <!--<div class="clear"></div>-->
          </div>
          <div>
            <h2>Appréciez le design sans contour </h2>
            <img src="img/product-1/desc-1.jpg" alt="zoom écran" class="main-left">
            <p>En plus du look moderne et attrayant qu'il procure, le design sans contour permet des configurations à plusieurs écrans sans interruption. Votre curseur, vos fenêtres ne sont plus perdus dans les abysses sombres des contours lorsque
              plusieurs écrans sont placés les uns à côté des autres. </p>
            <p> Le profil plat de ce moniteur AOC offre de nombreux avantages. Très élégant sous tous les angles, il devient un choix idéal dans les espaces publics. Sa finesse et sa conception moderne lui permettent d'occuper moins de place sur le bureau. </p>
          </div>
          <!--<div class="clear"></div>-->
          <div>
            <h2>Tout le confort nécessaire</h2>
            <img src="img/product-1/desc-2.jpg" alt="écran" class="main-right">
            <p> Agréable visuellement et intuitif, ce moniteur dispose également d'une dalle IPS. Cette dernière reproduit des couleurs éclatantes et offre de très larges angles de vue. De cette façon, les images gardent toujours un excellent aspect et une parfaite précision,
              quel que soit l'angle auquel vous regardez l'écran. </p>
            <p> Vous voulez utiliser votre écran même dans un environnement très lumineux, à côté d'une fenêtre au soleil par exemple ? La haute luminosité de 250 cd/m² garantit une bonne visibilité, même en conditions difficiles. </p>
          </div>
        </section>
      </div>
      <!-- END PRODUCT -->  
      </div><!-- end product --> 