<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Hitech - Admin</title>
       <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
         <link href="css/styles.css" rel="stylesheet" />
          <link href="assets/css/admin.css" rel="stylesheet" />
    </head>
    <body class="sb-nav-fixed">
	<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark"> <a class="navbar-brand" href="index.html"><img src="assets/img/front/logo.svg" height="20px" alt="Logo HiTech" > HiTech.NET</a>
		<h1 class="navbar-text">Dashboard</h1>
			<form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
				<div class="input-group">
					<div class="input-group-append"> </div>
				</div>
		    <ul class="navbar-nav ml-auto ml-md-0">
			  <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img class="avatar-48" src="" alt=""><i class="fas fa-user fa-fw"></i><small> &lt;&lt;avatar ici</small></a>
				<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown"> <a class="dropdown-item" href="#">Settings</a> <a class="dropdown-item" href="#">Profile</a>
				<div class="dropdown-divider"></div>
				<a class="dropdown-item" href="logout">Logout</a> </div>
			  </li>
		    </ul>
		    </form>
	</nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-light" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                          <div class="sb-sidenav-menu-heading"><i class="fas fa-home"></i> Accueil</div>
                          <a class="nav-link btn-block" href="dashboard"> Tableau de bord</a>
                          <div class="sb-sidenav-menu-heading"><i class="fas fa-globe-europe"></i> Site web</div>     
                          <a class="nav-link btn-block" href="boutique">Gestion des rubriques</a>
                          <a class="nav-link btn-block" href="#">Gestion des actualités</a>                        
                          <div class="sb-sidenav-menu-heading"><i class="fas fa-store-alt"></i> Boutique</div>
                          <!--a class="nav-link btn-block" href="boutique">  <div class="sb-nav-link-icon"></div>  Gestion des boutiques</a-->
                          <a class="nav-link btn-block" href="rayon">  <div class="sb-nav-link-icon"></div>  Gestion des rayons</a>
                          <a class="nav-link btn-block" href="productList">  <div class="sb-nav-link-icon"></div>  Gestion des produits</a>
                          <a class="nav-link btn-block" href="#">  <div class="sb-nav-link-icon"></div>  Gestion des commandes</a>   
                        </div>
                      </div>
                 </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
       
                        <ol class="card mb-4">
                            <li class="breadcrumb-item active">Dashboard &nbsp; <em> &gt;&nbsp; </em><?= $_GET['page'] ?></li>
                        </ol>
                    
                        <div class="row">
                            <div class="col-xl">
								<div class="card bg-light">
						        <div class="card-title">
						        </div>
					            <div class="card-body"><?php include $template; ?>
								</div>
				            </div>	
						</div> 
                    </div>
            </div>
                      
                </main>
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; HiTech <?= date("Y"); ?> </div>
                            
                        </div>
                    </div>
                </footer>
         
        </div>
        <?php// include $template; ?>
        <script
			  src="https://code.jquery.com/jquery-3.5.1.min.js"
			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
			  crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="assets/js/scripts.js"></script>
        <script src="assets/js/scriptAdmin.js"></script>
    </body>
</html>
