<!DOCTYPE html>
<html lang="fr">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<!-- à enlever ? -->
		<meta name="description" content="Un écran 23,8&quot; Full HD et sans bords; c'est sûrement votre futur moniteur pour la maison ou le bureau. AOC vous propose le 24B1XHS, un produit élégant au look doté d'une dalle VA avec un temps de réponse rapide de 7 ms en résolution 1920 x 1080 pixels. Cet écran WLED très fonctionnel offre un contenu avec un fréquence de 60 Hz, idéal pour tous les usages du quotidien.">
		
		<title>HiTech.NET</title>
		
		<link rel="icon" type="image/svg+xml" href="images/logo.svg">
		<link rel="stylesheet" href="css/normalize.css">
		 <!-- bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<!-- css pour le back à enlever ?
   		 <link rel="stylesheet" href="../assets/css/login.css" type="text/css" />
    	<link rel="stylesheet" href="../assets/css/admin.css" type="text/css" />
    	-->
    	<!-- front : css front-->
		<link rel="stylesheet" href="assets/css/front.css" type="text/css" />
		<!-- front : css pour la police-->
		<link rel="stylesheet" href="assets/css/font.css" type="text/css" />
		<!-- front : css pour les icones-->
		<link rel="stylesheet" href="assets/css/icons.css" type="text/css" />
		<!-- A enlever ?
		<meta property="og:description" content="Un écran 23,8&quot; Full HD et sans bords; c'est sûrement votre futur moniteur pour la maison ou le bureau. AOC vous propose le 24B1XHS, un produit élégant au look doté d'une dalle VA avec un temps de réponse rapide de 7 ms en résolution 1920 x 1080 pixels. Cet écran WLED très fonctionnel offre un contenu avec un fréquence de 60 Hz, idéal pour tous les usages du quotidien."
		/>
		<meta property="og:title" content="AOC 24B1XHS - HiTech.NET" />
		<meta property="og:image" content="https://www.hitech.net.com/images/product-1/slide-1-md.jpg" />
		<meta property="og:url" content="https://www.hitech.net.com/product-1.html" />
		-->
	</head>

	<body id="top" class="">
		<div class="hidden-menu">
			<a href="#top">Haut de page</a>
			<a href="#searchbar">Recherche</a>
			<a href="#toolbar">Mon compte</a>
			<a href="#menu">Menu principal</a>
			<a href="#toc">Sommaire</a>
		</div>
		
		<header class="header">
			<div class="container display">
				<div>Options d'affichage / accessiblité</div>
				<div>
					Thème&nbsp;:
					<button id="theme-dark">sombre contrasté</button>
					<button id="theme-none">clair</button>
				</div>
				<div>
					Interlignage&nbsp;:
					<button id="line-normal">simple</button>
					<button id="line-large">augmenté</button>
				</div>
			</div>
			<div class="container cols cols--4">
				<div class="logo">
					<img src="assets/img/front/logo.svg" alt="Logo HiTech.NET" width="64">
					<p>HiTech.NET</p>
					<p>Tout le matériel High-Tech</p>
				</div>
				<div id="searchbar" class="searchbar double hide-md" role="searchbox">
					<form action="product-1.html" method="post" novalidate="novalidate">
						<input name="query" type="text" placeholder="Chercher un produit, une marque...">
						<span>❯❯❯</span>
						<select name="store">
						<option value="0">Tous les rayons...</option>
						<option value="1">Ordinateurs</option>
						<option value="2">Péripheriques &amp; composants</option>
						<option value="3">Téléphones</option>
						<option value="4">Objets connectés</option>
					</select>
						<button><i class="icon-search"></i></button>
					</form>
				</div>
				<div id="toolbar" class="toolbar" role="toolbar">
					<a href="#" id="user-button"><i class="icon-user"></i>Mon compte</a>
					<a href="#" id="cart-button" class="cart-button"><i class="icon-cart"></i>Mon panier 
						<span>
							<?php if( isset($_SESSION['basket'])) 
								echo count($_SESSION['basket']); 
							?>
						</span>
					</a>
				</div>
			</div>
			<?php include 'views/navbar.phtml'?>
		</header>
		
		 <main>
               <?php include $template; ?>
   	     </main>
		
		<footer class="footer">
			<nav class="container menu">
				<ul class="cols cols--4">
					<li><a href="#"><i class="icon-display"></i>Ordinateurs</a></li>
					<li><a href="#"><i class="icon-data"></i>Péripheriques &amp; composants</a></li>
					<li><a href="#"><i class="icon-phone"></i>Téléphones</a></li>
					<li><a href="#"><i class="icon-clock"></i>Objets connectés</a></li>
				</ul>
			</nav>
			<div class="container cols cols--2 gutter">
				<section class="payment">
					<h2>Moyens de paiement</h2>
					<div>
						<span class="payment-mastercard"></span>
						<span class="payment-cb"></span>
						<span class="payment-visa"></span>
						<span class="payment-virement"></span>
					</div>
				</section>
				<section class="social">
					<h2>Sur les réseaux sociaux</h2>
					<div>
						<a href="#"><i class="icon-facebook"></i></a>
						<a href="#"><i class="icon-instagram"></i></a>
						<a href="#"><i class="icon-twitter"></i></a>
						<a href="#"><i class="icon-linkedin"></i></a>
					</div>
				</section>
				<nav>
					<h2>A propos</h2>
					<ul class="unstyled">
						<li><a href="#">Qui sommes-nous ?</a></li>
						<li><a href="#">Nos services</a></li>
						<li><a href="#">Contactez-nous</a></li>
					</ul>
				</nav>
				<nav>
					<h2>A propos</h2>
					<ul class="unstyled">
						<li><a href="#">Plan du site</a></li>
						<li><a href="#">Foire Aux Questions</a></li>
						<li><a href="#">Conditions générales de vente</a></li>
						<li><a href="#">Informations légales</a></li>
					</ul>
				</nav>
			</div>
			<div class="license container" role="article">
				<p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p>
				<p>Ce matériel pédagogique est la propriété de la <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">3W Academy</a>. Cet exercice a été réalisé par Stephane Pereck.</p>
			</div>
					 
		</footer>
		
		<section id="cart-modal" class="modal modal--sm cart-modal" role="dialog">
			<a href="#" class="close">&times;</a>
			<h2>Mon panier</h2>
			<div id="cart-empty">
				<p>Aucun article</p>
			</div>
			<div id="cart-table" class="hidden">
				<ul class="unstyled"></ul>
				<a href="#" class="button">valider la commande</a>
			</div>
		</section>
		
		<?php if(!isset($_COOKIE['test'])):?>
		 <div id="cookiebar" class="cookieShow"><p>Des cookies ?</p><button type="button" id="cookieOk">J'accepte !</button></div>
		    <?php endif; ?>
		
		
		<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="crossorigin="anonymous"></script>    
		<script src="assets/js/main.js"></script></body>
		<script src="assets/js/modal.js"></script>
		<script src="assets/js/gallery.js"></script>
		<script src="assets/js/cart.js"></script>
	<!--<script src="assets/js/canvas.js"></script> -->

	</body>
</html>
