<!DOCTYPE html>
<html lang="fr">

	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<meta name="description" content="Un écran 23,8&quot; Full HD et sans bords; c'est sûrement votre futur moniteur pour la maison ou le bureau. AOC vous propose le 24B1XHS, un produit élégant au look doté d'une dalle VA avec un temps de réponse rapide de 7 ms en résolution 1920 x 1080 pixels. Cet écran WLED très fonctionnel offre un contenu avec un fréquence de 60 Hz, idéal pour tous les usages du quotidien.">
		<title>AOC 24B1XHS - HiTech.NET</title>
		<link rel="icon" type="image/svg+xml" href="images/logo.svg">
		<link rel="stylesheet" href="css/normalize.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
   		 <link rel="stylesheet" href="../assets/css/login.css" type="text/css" />
    	<link rel="stylesheet" href="../assets/css/admin.css" type="text/css" />
		<link rel="stylesheet" href="assets/css/front.css" type="text/css" />
		<link rel="stylesheet" href="assets/css/font.css" type="text/css" />
		<link rel="stylesheet" href="assets/css/icons.css" type="text/css" />
		<meta property="og:description" content="Un écran 23,8&quot; Full HD et sans bords; c'est sûrement votre futur moniteur pour la maison ou le bureau. AOC vous propose le 24B1XHS, un produit élégant au look doté d'une dalle VA avec un temps de réponse rapide de 7 ms en résolution 1920 x 1080 pixels. Cet écran WLED très fonctionnel offre un contenu avec un fréquence de 60 Hz, idéal pour tous les usages du quotidien."
		/>
		<meta property="og:title" content="AOC 24B1XHS - HiTech.NET" />
		<meta property="og:image" content="https://www.hitech.net.com/images/product-1/slide-1-md.jpg" />
		<meta property="og:url" content="https://www.hitech.net.com/product-1.html" />
	</head>



	<body id="top" class="">
		<div class="hidden-menu">
			<a href="#top">Haut de page</a>
			<a href="#searchbar">Recherche</a>
			<a href="#toolbar">Mon compte</a>
			<a href="#menu">Menu principal</a>
			<a href="#toc">Sommaire</a>
		</div>
		<header class="header">
			<div class="container display">
				<div>Options d'affichage / accessiblité</div>
				<div>
					Thème&nbsp;:
					<button id="theme-dark">sombre contrasté</button>
					<button id="theme-none">clair</button>
				</div>
				<div>
					Interlignage&nbsp;:
					<button id="line-normal">simple</button>
					<button id="line-large">augmenté</button>
				</div>
			</div>
			<div class="container cols cols--4">
				<div class="logo">
					<img src="assets/img/front/logo.svg" alt="Logo HiTech.NET" width="64">
					<p>HiTech.NET</p>
					<p>Tout le matériel High-Tech</p>
				</div>
				<div id="searchbar" class="searchbar double hide-md" role="searchbox">
					<form action="product-1.html" method="post" novalidate="novalidate">
						<input name="query" type="text" placeholder="Chercher un produit, une marque...">
						<span>❯❯❯</span>
						<select name="store">
						<option value="0">Tous les rayons...</option>
						<option value="1">Ordinateurs</option>
						<option value="2">Péripheriques &amp; composants</option>
						<option value="3">Téléphones</option>
						<option value="4">Objets connectés</option>
					</select>
						<button><i class="icon-search"></i></button>
					</form>
				</div>
				<div id="toolbar" class="toolbar" role="toolbar">
					<a href="#" id="user-button"><i class="icon-user"></i>Mon compte</a>
					<a href="#" id="cart-button" class="cart-button"><i class="icon-cart"></i>Mon panier</a>
				</div>
			</div>
			<nav id="menu" class="menu container d-flex">
				<?php foreach($this->navBoutique as $boutique ):?>
				<ul class="d-flex flex-column cols cols--4">
					<li>
						<a href="#"><i class="icon-display"></i><?= $boutique["boutique"]?></a>
						<div>
							<ul>
								<?php foreach($this->navRayon as $rayon ):?>
								<?php if($boutique['idBoutique']==$rayon['idBoutique']):?>
								<li>
									<?= $rayon["rayon"]?>
										<ul>
											<?php foreach($this->navProduit as $product):?>
											<div class="navproduct">
												<?php if($rayon['idRayon']==$product['idRayon']):?>
												<li>
													<a href="<?=$product['id']?>">
														<?= $product["nom"]?>
													</a>
												</li>
												<?php endif; ?>
												<?php endforeach; ?>
										</ul>
										</div>
								</li>
						</div>
						<?php endif; ?>
						<?php endforeach; ?>
						</ul>
						</div>
					</li>
				</ul>
				<?php endforeach; ?>
			</nav>
		</header>
		
		 <main>

        <?php include $template; ?>
    </main>
		
		<footer class="footer">
			<nav class="container menu">
				<ul class="cols cols--4">
					<li><a href="#"><i class="icon-display"></i>Ordinateurs</a></li>
					<li><a href="#"><i class="icon-data"></i>Péripheriques &amp; composants</a></li>
					<li><a href="#"><i class="icon-phone"></i>Téléphones</a></li>
					<li><a href="#"><i class="icon-clock"></i>Objets connectés</a></li>
				</ul>
			</nav>
			<div class="container cols cols--2 gutter">
				<section class="payment">
					<h2>Moyens de paiement</h2>
					<div>
						<span class="payment-mastercard"></span>
						<span class="payment-cb"></span>
						<span class="payment-visa"></span>
						<span class="payment-virement"></span>
					</div>
				</section>
				<section class="social">
					<h2>Sur les réseaux sociaux</h2>
					<div>
						<a href="#"><i class="icon-facebook"></i></a>
						<a href="#"><i class="icon-instagram"></i></a>
						<a href="#"><i class="icon-twitter"></i></a>
						<a href="#"><i class="icon-linkedin"></i></a>
					</div>
				</section>
				<nav>
					<h2>A propos</h2>
					<ul class="unstyled">
						<li><a href="#">Qui sommes-nous ?</a></li>
						<li><a href="#">Nos services</a></li>
						<li><a href="#">Contactez-nous</a></li>
					</ul>
				</nav>
				<nav>
					<h2>A propos</h2>
					<ul class="unstyled">
						<li><a href="#">Plan du site</a></li>
						<li><a href="#">Foire Aux Questions</a></li>
						<li><a href="#">Conditions générales de vente</a></li>
						<li><a href="#">Informations légales</a></li>
					</ul>
				</nav>
			</div>
			<div class="license container" role="article">
				<p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p>
				<p>Ce matériel pédagogique est la propriété de la <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">3W Academy</a>. Cet exercice a été réalisé par Stephane Pereck.</p>
			</div>
		</footer>
		 <?php if(!isset($_COOKIE['test'])):?>
    <div id="cookiebar" class="cookieShow"><p>lorem ipsum</p><button type="button" id="cookieOk">J'accepte !</button></div>
    <?php endif; ?>
		
		
		
		
		<!-- class modal -->
		
		<div id="modal-backdrop" class="modal-backdrop"></div>
		<section id="user-modal" class="modal modal--sm user-modal" role="dialog">
			<a href="#" class="close">&times;</a>
			<h2>Mon compte</h2>
			<form action="product-1.html">
				<fieldset>
					<legend>J'ai déjà un compte</legend>
					<div class="field">
						<label>Mon adresse email</label>
						<div class="value"><input name="login" type="text"></div>
					</div>
					<div class="field">
						<label>Mon mot de passe</label>
						<div class="value"><input name="password" type="password"></div>
					</div>
					<div class="field">
						<div class="first"><button class="button">Se connecter</button></div>
						<div class="value"><a href="#">J'ai oublié mon mot de passe</a></div>
					</div>
				</fieldset>
				<fieldset>
					<legend>Je n'ai pas de compte</legend>
					<div class="field"><button class="button">Créer un compte</button></div>
				</fieldset>
			</form>
		</section>
		<section id="cart-modal" class="modal modal--sm cart-modal" role="dialog">
			<a href="#" class="close">&times;</a>
			<h2>Mon panier</h2>
			<div id="cart-empty">
				<p>Aucun article</p>
			</div>
			<div id="cart-table" class="hidden">
				<ul class="unstyled"></ul>
				<a href="#" class="button">valider la commande</a>
			</div>
		</section>
		<section id="gallery-modal" class="modal modal--lg" role="dialog">
			<a href="#" class="close">&times;</a>
			<h2>AOC 24B1XHS</h2>
			<div id="gallery-2" class="gallery gallery--left gallery--modal">
				<div><img src="images/product-1/slide-1-lg.jpg" alt="AOC 24B1XHS : Vue du produit 1"></div>
				<ul>
					<li>
						<a href="images/product-1/slide-1-lg.jpg"><img src="images/product-1/slide-1-md.jpg" alt="AOC 24B1XHS : Vignette du produit 1"></a>
					</li>
					<li>
						<a href="images/product-1/slide-2-lg.jpg"><img src="images/product-1/slide-2-md.jpg" alt="AOC 24B1XHS : Vignette du produit 2"></a>
					</li>
					<li>
						<a href="images/product-1/slide-3-lg.jpg"><img src="images/product-1/slide-3-md.jpg" alt="AOC 24B1XHS : Vignette du produit 3"></a>
					</li>
					<li>
						<a href="images/product-1/slide-4-lg.jpg"><img src="images/product-1/slide-4-md.jpg" alt="AOC 24B1XHS : Vignette du produit 4"></a>
					</li>
					<li>
						<a href="images/product-1/slide-5-lg.jpg"><img src="images/product-1/slide-5-md.jpg" alt="AOC 24B1XHS : Vignette du produit 5"></a>
					</li>
				</ul>
			</div>
		</section>
		
		
		
		
		
		
		
<script
			  src="https://code.jquery.com/jquery-3.5.1.min.js"
			  integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
			  crossorigin="anonymous"></script>    
<script src="assets/js/main.js"></script></body>
		<script src="assets/js/modal.js"></script>
		<script src="assets/js/gallery.js"></script>
		<script src="assets/js/cart.js"></script>
		<script src="assets/js/canvas.js"></script>
	
	
	
	
	
		<script>
			var modal0 = new Modal('#user-modal', '#modal-backdrop');
			modal0.addTrigger('#user-button', 'open');
			modal0.addTrigger('#user-modal .close', 'close');

			var modal1 = new Modal('#cart-modal', '#modal-backdrop');
			modal1.addTrigger('#cart-button', 'open');
			modal1.addTrigger('#cart-modal .close', 'close');

			var modal2 = new Modal('#gallery-modal', '#modal-backdrop');
			modal2.addTrigger('#gallery-1 > div img', 'open');
			modal2.addTrigger('#gallery-modal .close', 'close');

			var gallery1 = new Gallery('#gallery-1 > div img', '#gallery-1 > ul a');
			var gallery2 = new Gallery('#gallery-2 > div img', '#gallery-2 > ul a');

			var cart = new Cart('#cart-button', '#cart-table', '#cart-empty');
			cart.addProduct('product-1', 'AOC 24B1XHS Black', 109.94);
			cart.addTrigger('#add-cart', 'addToCart', 'product-1');
			cart.addTrigger('#add-wish', 'addToWish', 'product-1');
			cart.restore();
			cart.update();

			var body = document.querySelector('body');
			document.getElementById('theme-dark').addEventListener('click', function(event) {
				body.classList.add('theme-dark');
			}, false);
			document.getElementById('theme-none').addEventListener('click', function(event) {
				body.classList.remove('theme-dark');
			}, false);
			document.getElementById('line-large').addEventListener('click', function(event) {
				body.classList.add('line-large');
			}, false);
			document.getElementById('line-normal').addEventListener('click', function(event) {
				body.classList.remove('line-large');
			}, false);
		</script>
	</body>

</html>
