<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Hight tech</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="../../assets/css/login.css" type="text/css" />
    <link rel="stylesheet" href="../../assets/css/admin.css" type="text/css" />
</head>

<body>
    <header>
       <?php include $templateNav; ?>
      
    </header>
    <aside></aside>
    <main class="container">
      <div class="breadcrumbs">
        <a href="#"><img src="images/icons/home.svg" alt="home icon">Accueil</a><strong>&gt;</strong><a href="#"><img src="images/icons/database.svg" alt="dabase icon">$nom_boutique</a><strong>&gt;</strong><a href="#"><img src="images/icons/computer.svg" alt="computer icon">$nom_rayon</a><strong>&gt;</strong>
      </div>
    
       <!-- article -->

         <?php include $template; ?>
    </main>
    
    <footer></footer>
</body>
</html>



