<div class="col-4 tools">
<form>
    <input class="search" type="search" name="search"/>
    <button class="btn btn-outline-info btn-sm" type='submit'>Rechercher</button>
</form>

<button class="btn btn-primary btn-sm add" type="submit"><a href="addProduct"><i class="far fa-plus-square"></i> Ajouter un produit</a></button> 
</div>
<table>
    <thead>
        <th>Produit</th>
        <th>Rayon</th>
        <th>Boutique</th>
        <th class="col-1 statutp">Statut</th>
        <th colspan="3">Actions</th>
	
    </thead>
    <tbody class="table-striped">
    <?php foreach($productLists as $produit):?>
    <tr scope="row">
        <td class="col-3" scope="col"><?=htmlspecialchars($produit['marque'])?> <?=htmlspecialchars($produit['nom'])?></td>
       <td class="col-2" scope="col"><?=htmlspecialchars($produit['rayon'])?></td>
      <td class="col-1" scope="col"><?=htmlspecialchars($produit['boutique'])?></td>
      <td class="col-1 statutNom" scope="col"><?= $this -> colorStatut(htmlspecialchars($produit['statut']))?></td>
      <td class="col-2"><?= $this -> setButton(htmlspecialchars($produit['statut']),htmlspecialchars($produit['id'])); ?></td> 
      <td class="col-1"><button class="btn btn-outline-secondary btn-sm btn-block"><i class="fas fa-pen"></i> Modifier</button></td>
      <td class="col-2"><button class="btn btn-outline-info btn-sm btn-block"><i class="fas fa-tags"></i> Caractéristiques</button></td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>