<div class="col-4 tools">
<form>
    <input class="search" type="search" name="search"/><button class="btn btn-outline-info btn-sm" type='submit'>Rechercher</button>
</form>
<button class="btn btn-primary btn-sm add" type="submit"><a href="addRayon"><i class="fas fa-plus-square"></i>  Ajout. rayon</a></button> 
</div>

<!--button type="submit"><a href="addRayon">+ Ajouter un rayon</a></button--> 

<table class="col-4" >
  <thead>
    <th class="col-2">Rayon</th>
    
    <th colspan="3">Actions</th>
   </thead>
  
  <tbody class="table-striped">
    <?php foreach($rayons as $rayon):?>
    <tr scope="row">
      <td scope="col"><?= htmlspecialchars($rayon["nom"])?></td>
      <td class="col-1"><button class="btn btn-outline-secondary btn-sm btn-block"><a href="updateRayon-<?= htmlspecialchars($rayon["id_rayon"])?>">Modifier</a></button></td>
      <td class="col-1"><button class="btn btn-outline-danger btn-sm btn-block"><a href="deleteRayon-<?= htmlspecialchars($rayon["id_rayon"])?>" class="suppr">Supprimer</a></button></td>
      <td class="col-1"><button class="btn btn-outline-info btn-sm btn-block"><a href="#" data-id="<?= htmlspecialchars($rayon["id_rayon"])?>" class="supprBis">Suppr. Bis</a></button></td>  
        
    </tr>
    <?php endforeach; ?>
</tbody>
</table>
<div class="col-4 tools">
<form>
    <input class="search" type="search" name="search"/><button class="btn btn-outline-info btn-sm" type='submit'>Rechercher</button>
</form>
<button class="btn btn-primary btn-sm add" type="submit"><a href="addRayon"><i class="fas fa-plus-square"></i>  Ajout. rayon</a></button> 
</div>