<form>
    <input type="search" name="search"/>
   <button type='submit'>Rechercher</button>
</form>

<button type="submit"><a href="addRayon">+ Ajouter un rayon</a></button> 

<table>
    <thead>
        <th>Rayon</th>
        <th>Actions</th>
    </thead>
    <tbody>
    <?php foreach($rayons as $rayon):?>
    <tr scope="row">
        <td scope="col"><?= $rayon["nom"]?></td>
        <td><button><a href="updateRayon-<?=$rayon["id_rayon"]?>">Modifier</a></button></td>
        <td><button><a href="deleteRayon-<?=$rayon["id_rayon"]?>" class="suppr">Supprimer</a></button></td>
        
         <td><button><a href="#" data-id="<?=$rayon["id_rayon"]?>" class="supprBis">Supprimer Bis</a></button></td>
    </tr>
    <?php endforeach; ?>
</tbody>
</table>