<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dashboard</title>
</head>
<body>
    

<div>
  <button><a href="logout">Log Out</a></button>  
</div>


<div>
<h2>Accueil</h2>
<a href="dashboard">Tableau de bord</a>

<h2>Site web</h2>
<a href="">Gestion des rubriques</a>
<a href="">Gestion des actualités</a>

<h2>Boutique</h2>
<a href="">Gestion des rayons</a>
<a href="productList">Gestion des produits</a>
<a href="">Gestion des commandes</a>

<h2>Paramètres</h2>
<a href="">Gestion des utilisateurs</a>
<a href="">Gestion des rôles</a>
<a href="">Préférences</a>
</div>


<div>
   <?php include $template; ?>
</div>


</body>
<script src="../js/scriptAdmin.js"></script>
</html>
